# frontend/docker-compose.yml
version: '3.8'

services:
  angular:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    container_name: exam_angular
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - API_URL=http://localhost:8080/api/
    command: npm start