api_platform:
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
    docs_formats:
        jsonld:   ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html:     ['text/html']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    enable_docs: true
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']